Repository pivotal-cf/docs-ksm, pull requests merged in 2020-07, with the labels that each got.

#62 add prereq for default storage class on cluster (and link to tkgi spe…
  installing-helm.html.md.erb
Labels: unscheduled

#63 Add some clarity for helm install.
  installing-helm.html.md.erb
Labels: unscheduled

#64 Add some clarity for helm install.
  installing-helm.html.md.erb
Labels: unscheduled

#65 prometheus instructions
  installing-helm.html.md.erb
Labels: unscheduled

#66 Fixing prometheus query
  installing-helm-lab.html.md.erb
  installing-helm.html.md.erb
Labels: unscheduled

#68 Update for external Postgres
  installing-helm.html.md.erb
Labels: unscheduled

#67 Remove references to tile. Add some details to the reference architecture
  architecture.html.md.erb
  images/reference_architecture.png
  images/reference_architecture_k8s.png
  index.html.md.erb
  installing-helm-lab.html.md.erb
  installing-helm.html.md.erb
  installing.html.md.erb
  prepare-offer.html.md.erb
  upgrading.html.md.erb
Labels: scheduled

#70 Add correct values for image credentials.
  installing.html.md.erb
Labels: unscheduled

#69 Document the command for loading tgz image files
  installing.html.md.erb
Labels: unscheduled

#71 Removing command ksm logs in favor of kubectl logs
  troubleshoot.html.md.erb
Labels: unscheduled

#72 Add missing namespace param on installation page
  installing.html.md.erb
Labels: unscheduled

#73 Fix postgres image doc issues
  installing.html.md.erb
Labels: in progress

#74 Update limitation text
  index.html.md.erb
Labels: unscheduled

#75 Remove redundant steps from helm install
  installing.html.md.erb
Labels: unscheduled

#76 tls configuration
  installing.html.md.erb
Labels: unscheduled

#78 Splitting production and lab into two different docs
  installing-lab.html.md.erb
  installing.html.md.erb
  using.html.md.erb
Labels: unscheduled
